FROM ubuntu:18.04

LABEL maintainer "bamboog130"

ARG version="26.2"

ENV DEBCONF_NOWARNINGS yes
ENV DEBIAN_FRONTEND noninteractive

WORKDIR /tmp

# change apt source
RUN sed -i.bak -e "s%http://.*.ubuntu.com/ubuntu/%http://ftp.jaist.ac.jp/pub/Linux/ubuntu/%g" /etc/apt/sources.list \
&& apt-get update && apt-get install -y --no-install-recommends \
  gcc \
  make \
  ncurses-dev \
  libgif-dev \
  libgnutls28-dev \
  libgtk2.0-dev \
  libjpeg-dev \
  libtiff-dev \
  libxml2-dev \
  libxpm-dev \
  wget \
&& apt-get clean && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/* \
&& wget -O - http://ftp.jaist.ac.jp/pub/GNU/emacs/emacs-${version}.tar.gz | tar zxf - \
&& cd emacs-${version} \
&& ./configure --with-x-toolkit=gtk2 \
&& make -j \
&& make prefix=/tmp/installed-emacs install
